version: '3.8'

services:
  jupyter-pyspark:
    image: pramonettivega/pyspark-ml-courselet:latest
    user: jovyan
    environment:
      GRANT_SUDO: "yes"
    ports:
      - "8888:8888"
    volumes:
      - data:/home/jovyan/data
      - tmp:/home/jovyan/tmp
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    networks:
      - spark-network

  spark-master:
    image: pramonettivega/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "8080:8080"
    volumes:
      - data:/home/jovyan/data
      - tmp:/home/jovyan/tmp
    networks:
      - spark-network

  spark-worker-1:
    image: pramonettivega/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - data:/home/jovyan/data
      - tmp:/home/jovyan/tmp
    networks:
      - spark-network

  spark-worker-2:
    image: pramonettivega/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - data:/home/jovyan/data
      - tmp:/home/jovyan/tmp
    networks:
      - spark-network

volumes:
  data:
    driver: local
  tmp:
    driver: local

networks:
  spark-network:
    driver: bridge